version: '3.6'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: docker
      PGDATABASE: FastFeet
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: redis
    ports: 
      - 6379:6379    
    networks:
      - backend

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastfeet-api
    depends_on:
      - db
      - redis
    ports:
      - 5556:5556
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
