version: '3.6'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: FastFeet
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports: 
      - 6379:6379    
    networks:
      - backend

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastfeet-api
    depends_on:
      - db
      - redis
    ports:
      - 5555:5555
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
