version: '3.6'

services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=FastFeet
    ports:
      - "5432:5432"
