const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'FastFeet API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:5555',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Order',
      description: 'Endpoints for orders',
    },
    {
      name: 'Recipient',
      description: 'Endpoints for recipients',
    },
    {
      name: 'Delivery',
      description: 'Endpoints for delivery',
    },
    {
      name: 'Delivery Issues',
      description: 'Endpoints delivery issues',
    },
    {
      name: 'Delivery Man',
      description: 'Endpoints delivery man',
    },
    {
      name: 'Session',
      description: 'Endpoints Session',
    },
  ],
  definitions: {
    addOrder: {
      $product: '',
      $recipient_id: 0,
      $deliveryman_id: 0,
    },
    updateOrder: {
      $id: 0,
      $product: '',
      $recipient_id: 0,
      $deliveryman_id: 0,
    },
    deleteOrder: {
      $id: 0,
    },
    get: {},
    findByProductName: {
      $product: '',
    },
    findById: {
      $id: 0,
    },
  },
};

const outputFile = 'swagger_output.json';
const endpointsFiles = ['src/routes.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
